// This file has been autogenerated from a class added in the UI designer.

using System;
using System.Net.Http;
using Channel9.Model;
using Channel9.Core.Services;
using Foundation;
using UIKit;

namespace Channel9
{
	public partial class EpisodeCell : UITableViewCell
	{
		public EpisodeCell (IntPtr handle) : base (handle)
		{
		}

        public async void Configure( Entry episode )
        {
            thumbnailImage.ClipsToBounds = true;
            thumbnailImage.Layer.CornerRadius = 15;
            //
            titleLabel.Text = episode.Title;
            summaryLabel.Text = episode.NoHTMLBody;

            thumbnailImage.Image = null;
            var byteImage = await ContentService.DownloadImageArrayAsync(episode.MediumThumbnail);
            thumbnailImage.Image = UIImage.LoadFromData(NSData.FromArray(byteImage));
        }
	}
}
