// This file has been autogenerated from a class added in the UI designer.

using System;
using Channel9.Core.Model;
using Channel9.Core.Services;
using Foundation;
using UIKit;

namespace Channel9
{
	public partial class EventCell : UICollectionViewCell
	{
		public EventCell (IntPtr handle) : base (handle)
		{
		}

        public async void Configure(Event evento)
        {
			//
            titleLabel.Text = evento.DisplayName;
            imageView.Image = null;
            var imageUrl = evento.WidescreenThumbnailImage ?? (evento.ThumbnailImage ?? evento.SmallThumbnailImage);
            if (String.IsNullOrEmpty(imageUrl))
            {
                imageView.Image = UIImage.FromBundle("noimage");
			} else {
				var byteImage = await ContentService.DownloadImageArrayAsync(imageUrl);
				imageView.Image = UIImage.LoadFromData(NSData.FromArray(byteImage));
			}
        }
	}
}
