// This file has been autogenerated from a class added in the UI designer.

using System;
using System.Net.Http;
using Channel9.Model;
using Channel9.Core.Services;
using Foundation;
using UIKit;

namespace Channel9
{
	public partial class FeaturedCell : UICollectionViewCell
	{
		public FeaturedCell (IntPtr handle) : base (handle)
		{
            
		}

        public async void Configure(IPlayableItem featured)
        {
            labelCaption.Text = $"Rating: {featured.Rating.ToString("N2")}";
            labelDescription.Text = featured.Title;
			//
			imageView.Image = null;
            if (String.IsNullOrEmpty(featured.ThumbnailImage))
            {
                imageView.Image = UIImage.FromBundle("noimage");
            } else {
				var byteImage = await ContentService.DownloadImageArrayAsync(featured.ThumbnailImage);
				imageView.Image = UIImage.LoadFromData(NSData.FromArray(byteImage));
			}
        }
	}
}
