// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace Channel9
{
	public partial class SimpleGroupHeader : UICollectionReusableView
	{
		public SimpleGroupHeader (IntPtr handle) : base (handle)
		{
		}

        public void Configure(string title)
        {
            this.sectionTitle.Text = title;
        }
	}
}
